version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: custom-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - django_app
    restart: always

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: notes-app:latest
    container_name: notes_app
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - "8000"
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: curl -f http://localhost:8000/admin || exit 1
      interval: 30s
      timeout: 1
